services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: developement
    command: npm run start:dev reservations
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
